FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

COPY . .

RUN npx nx run frontend:build --configuration=production

FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

COPY --from=builder /app/dist/apps/frontend ./dist/apps/frontend

EXPOSE 4000

CMD ["node", "dist/apps/frontend/server/server.mjs"]
