FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npx nx run frontend:build --configuration=production

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist/apps/frontend ./dist/apps/frontend

EXPOSE 4000

CMD ["node", "dist/apps/frontend/server/server.mjs"]
