FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

COPY . .

RUN npx nx run backend:build --configuration=production

FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist/apps/backend ./

# TypeORM در runtime به درایور postgres نیاز دارد.
RUN npm ci --omit=dev && npm install pg --omit=dev --no-save

EXPOSE 5000

CMD ["node", "main.js"]
